# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LifeTomorrow Caregiver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LifeTomorrow Caregiver
  pod 'MessageKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

  pod 'Alamofire'
  pod 'Kingfisher'

end
