# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LifeTomorrow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LifeTomorrow
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'ResearchKit', '~> 2.1'
  pod 'CareKit', '~> 1.2'

end

target 'LifeTomorrowWatch Watch App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LifeTomorrowWatch Watch App

end
